import math
import warnings
import collections.abc
from itertools import repeat
from typing import Sequence, Union, List

import numpy as np
import torch
import torch.nn as nn

# --- Helper Functions (Copied/Adapted from MONAI) ---

def _ntuple(n):
    """
    Creates a function that converts input to an n-tuple.
    From PyTorch internals.
    """
    def parse(x):
        if isinstance(x, collections.abc.Iterable) and not isinstance(x, str):
            return tuple(x)
        return tuple(repeat(x, n))
    return parse

def _ensure_tuple_rep(tup, dim):
    """Returns a tuple of length dim"""
    if isinstance(tup, collections.abc.Iterable) and not isinstance(tup, str):
        if len(tup) == dim:
            return tuple(tup)
        else:
            raise ValueError(f"Sequence must have length {dim}, got {len(tup)}.")
    else:
        return tuple(repeat(tup, dim))

def trunc_normal_(tensor: torch.Tensor, mean: float = 0.0, std: float = 1.0, a: float = -2.0, b: float = 2.0) -> torch.Tensor:
    """
    Fills the input Tensor with values drawn from a truncated
    normal distribution. Sourced from PyTorch discussions and TIMM.
    Args:
        tensor: an n-dimensional torch Tensor
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    """
    def norm_cdf(x):
        return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
            "The distribution of values may be incorrect.",
            stacklevel=2,
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure values are within the specified range
        tensor.clamp_(min=a, max=b)
        return tensor

def build_sincos_position_embedding(
    grid_size: Union[int, List[int]], embed_dim: int, spatial_dims: int = 3, temperature: float = 10000.0
) -> torch.nn.Parameter:
    """
    Builds a sin-cos position embedding based on the given grid size, embed dimension, spatial dimensions, and temperature.
    Reference: https://github.com/cvlab-stonybrook/SelfMedMAE/blob/68d191dfcc1c7d0145db93a6a570362de29e3b30/lib/models/mae3d.py

    Args:
        grid_size (List[int]): The size of the grid in each spatial dimension.
        embed_dim (int): The dimension of the embedding.
        spatial_dims (int): The number of spatial dimensions (must be 3 for this context).
        temperature (float): The temperature for the sin-cos position embedding.

    Returns:
        pos_embed (nn.Parameter): The sin-cos position embedding as a fixed parameter.
    """
    if spatial_dims != 3:
         raise ValueError(f"This implementation currently only supports spatial_dims=3, got {spatial_dims}")

    to_3tuple = _ntuple(3)
    grid_size_t = to_3tuple(grid_size)
    h, w, d = grid_size_t
    grid_h = torch.arange(h, dtype=torch.float32)
    grid_w = torch.arange(w, dtype=torch.float32)
    grid_d = torch.arange(d, dtype=torch.float32)

    grid_h, grid_w, grid_d = torch.meshgrid(grid_h, grid_w, grid_d, indexing='ij') # Use 'ij' indexing

    if embed_dim % 6 != 0:
        raise ValueError(f"Embed dimension {embed_dim} must be divisible by 6 for 3D sin-cos position embedding")

    pos_dim = embed_dim // 6
    omega = torch.arange(pos_dim, dtype=torch.float32) / pos_dim
    omega = 1.0 / (temperature**omega)

    # Flatten grids before einsum
    grid_h_flat = grid_h.flatten()
    grid_w_flat = grid_w.flatten()
    grid_d_flat = grid_d.flatten()

    out_h = torch.einsum("m,d->md", grid_h_flat, omega)
    out_w = torch.einsum("m,d->md", grid_w_flat, omega)
    out_d = torch.einsum("m,d->md", grid_d_flat, omega)

    pos_emb = torch.cat(
        [
            torch.sin(out_w), torch.cos(out_w),
            torch.sin(out_h), torch.cos(out_h),
            torch.sin(out_d), torch.cos(out_d),
        ],
        dim=1,
    )[None, :, :]

    pos_embed = nn.Parameter(pos_emb)
    pos_embed.requires_grad = False

    return pos_embed

# --- Main Function ---

def create_position_embedding(
    img_size: Sequence[int],
    patch_size: Sequence[int],
    hidden_size: int,
    pos_embed_type: str = "learnable",
    spatial_dims: int = 3,
) -> nn.Parameter:
    """
    Generates position embeddings for a 3D ViT model.

    Args:
        img_size (Sequence[int]): Dimension of the input image (e.g., [D, H, W]).
        patch_size (Sequence[int]): Dimension of the patch size (e.g., [pD, pH, pW]).
        hidden_size (int): Dimension of the hidden layer (embedding dimension).
        pos_embed_type (str): Position embedding type: "learnable" or "sincos".
                               Defaults to "learnable".
        spatial_dims (int): Number of spatial dimensions (should be 3). Defaults to 3.

    Returns:
        nn.Parameter: The position embedding parameter.

    Raises:
        ValueError: If img_size or patch_size cannot be represented as 3D tuples.
        ValueError: If any image dimension is not divisible by the corresponding patch dimension.
        ValueError: If pos_embed_type is not "learnable" or "sincos".
        ValueError: If pos_embed_type is "sincos" and hidden_size is not divisible by 6.
    """
    if spatial_dims != 3:
        raise ValueError(f"This function currently only supports spatial_dims=3, got {spatial_dims}")

    img_size_3d = _ensure_tuple_rep(img_size, 3)
    patch_size_3d = _ensure_tuple_rep(patch_size, 3)

    grid_size = []
    for i_s, p_s in zip(img_size_3d, patch_size_3d):
        if i_s % p_s != 0:
            raise ValueError(f"Image dimension {i_s} must be divisible by patch dimension {p_s}.")
        grid_size.append(i_s // p_s)

    n_patches = int(np.prod(grid_size))

    if pos_embed_type == "learnable":
        position_embeddings = nn.Parameter(torch.zeros(1, n_patches, hidden_size))
        trunc_normal_(position_embeddings, mean=0.0, std=0.02, a=-2.0, b=2.0)
        position_embeddings.requires_grad = True # Explicitly set for clarity
        return position_embeddings
    elif pos_embed_type == "sincos":
        if hidden_size % 6 != 0:
             raise ValueError(f"For 'sincos' embeddings in 3D, hidden_size ({hidden_size}) must be divisible by 6.")
        # build_sincos_position_embedding already returns nn.Parameter with requires_grad=False
        return build_sincos_position_embedding(grid_size, hidden_size, spatial_dims=3)
    else:
        raise ValueError(f"Unsupported pos_embed_type: {pos_embed_type}. Choose 'learnable' or 'sincos'.")

if __name__ == '__main__':
    # Example Usage
    image_dimensions = (96, 96, 96)
    patch_dimensions = (16, 16, 16)
    hidden_dim = 768 # Must be divisible by 6 for sincos

    print(f"Image Size: {image_dimensions}")
    print(f"Patch Size: {patch_dimensions}")
    print(f"Hidden Size: {hidden_dim}\\n")

    # --- Learnable Example ---
    try:
        learnable_pos_embed = create_position_embedding(
            img_size=image_dimensions,
            patch_size=patch_dimensions,
            hidden_size=hidden_dim,
            pos_embed_type="learnable"
        )
        print(f"Learnable Position Embedding:")
        print(f"  - Shape: {learnable_pos_embed.shape}") # Expected: (1, 6*6*6, 768) = (1, 216, 768)
        print(f"  - Requires Grad: {learnable_pos_embed.requires_grad}") # Expected: True
    except ValueError as e:
        print(f"Error creating learnable embeddings: {e}")

    print("-" * 20)

    # --- SinCos Example ---
    try:
        sincos_pos_embed = create_position_embedding(
            img_size=image_dimensions,
            patch_size=patch_dimensions,
            hidden_size=hidden_dim,
            pos_embed_type="sincos"
        )
        print(f"SinCos Position Embedding:")
        print(f"  - Shape: {sincos_pos_embed.shape}") # Expected: (1, 216, 768)
        print(f"  - Requires Grad: {sincos_pos_embed.requires_grad}") # Expected: False
    except ValueError as e:
        print(f"Error creating sincos embeddings: {e}")

    print("-" * 20)

     # --- Example with invalid hidden_size for sincos ---
    invalid_hidden_dim = 767
    print(f"Testing invalid hidden_size ({invalid_hidden_dim}) for sincos:")
    try:
        sincos_pos_embed_invalid = create_position_embedding(
            img_size=image_dimensions,
            patch_size=patch_dimensions,
            hidden_size=invalid_hidden_dim,
            pos_embed_type="sincos"
        )
    except ValueError as e:
        print(f"  - Successfully caught error: {e}") 